server:
  port : 9002
 
spring:
 application:
  name: MONITOR-PLAN-SERVICE
  
eureka:
   client:
      serviceUrl:
         defaultZone: http://18.141.137.69:8761/eureka
      instance:
      preferIpAddress: true